# Bot Setting
bot-token: Please-Replace-Here-To-Bot-Token #botのトークンをここに書いてください
# Server Setting
server-id: 0 #Server-ID
server-channel-text: 0 #Alarm-Channel(Text)-ID
server-channel-voice: 0 #Alarm-Channel(Voice)-ID
#Dev Setting
dev-debug-mode: false #debug-mode(true|false)
dev-channel-text: 0 #Dev-Alarm-Channel(Text)-ID
dev-channel-voice: 0 #Dev-Alarm-Channel(Text)-ID
